Rework start shell script to search the right python interpreter

diff --git a/wxglade b/wxglade
--- a/wxglade
+++ b/wxglade
@@ -13,11 +13,41 @@
 #  2. in the module directory of the current Python
 #  3. in a parallel Python module directory
 
-PYTHON_BIN=${PYTHON_BIN:=python2}
+# search order for Python interpreter
+INTERPRETER_LIST="python2 \
+                  python2.7 python27 \
+                  python2.6 python26 \
+                  python2.5 python25 \
+                  python2.4 python24 \
+                  python"
 
-${PYTHON_BIN} --version > /dev/null 2>&1
-if [ $? -ne 0 ]; then
-  echo "ERROR: Python interpreter \"${PYTHON_BIN}\" not found!"
+# Use the binary from PYTHON_BIN, if this environment variable is set
+if [ "$PYTHON_BIN" ]; then
+  INTERPRETER_LIST="$PYTHON_BIN"
+fi
+
+for INTERPRETER in $INTERPRETER_LIST; do
+  ${INTERPRETER} -V >/dev/null 2>&1
+  if [ $? -ne 0 ]; then
+    continue
+  fi
+
+  # check if interpreter is for Python 2
+  ${INTERPRETER} -V 2>&1 | grep -q "Python 2"
+  if [ $? -ne 0 ]; then
+    continue
+  fi
+  
+  # Python 2 interpreter found
+  PYTHON_BIN=$INTERPRETER
+
+  break
+done
+
+
+if [ ! "$PYTHON_BIN" ]; then
+  echo "ERROR: No interpreter for Python 2 found!"
+  echo "       Please install Python 2 to run wxGlade!"
   exit 1
 fi
 
@@ -25,25 +55,32 @@ fi
 PY_VERSION=$(${PYTHON_BIN} -c 'import sys; print sys.version[:3]')
 
 # determined prefix of the Python module directory structure
-if [ -e /etc/debian_version ]; then
-  WXGLADE_MODULE_PATH="/usr/lib/pymodules/python${PY_VERSION}/wxglade"
+if [ -d "/usr/lib/pymodules/python${PY_VERSION}/wxglade" ]; then
+  WXG_MODULE_PATH="/usr/lib/pymodules/python${PY_VERSION}/wxglade"
 else
-  WXGLADE_MODULE_PATH="/usr/lib/python${PY_VERSION}/wxglade"
+  WXG_MODULE_PATH="/usr/lib/python${PY_VERSION}/wxglade"
 fi
 
-CURR_DIR=$(dirname $0)
-
 # search wxglade.py
-if [ -e "${CURR_DIR}/wxglade.py" ]; then
-  WXG_PATH="${CURR_DIR}/wxglade.py"
-elif [ -e "${WXGLADE_MODULE_PATH}/wxglade.py" ]; then
-  WXG_PATH="${WXGLADE_MODULE_PATH}/wxglade.py"
-elif [ -e "${CURR_DIR}/../lib/python${PY_VERSION}/site-packages/wxglade/wxglade.py" ]; then
-  WXG_PATH="${CURR_DIR}/../lib/python${PY_VERSION}/site-packages/wxglade/wxglade.py"
-else
+# dist-packages is only used in Debian and Debian derivates
+CURR_DIR=$(dirname "$0")
+for DIR in \
+   "${CURR_DIR}" \
+   "${WXG_MODULE_PATH}" \
+   "${CURR_DIR}/../lib/python${PY_VERSION}/site-packages/wxglade" \
+   "${CURR_DIR}/../lib/python${PY_VERSION}/dist-packages/wxglade" \
+   ; do
+  BINARY="${DIR}/wxglade.py"
+  if [ -x "${BINARY}" ]; then
+    WXG_BINARY="$BINARY"
+    break
+  fi
+done
+
+if [ ! "${WXG_BINARY}" ]; then
   echo "ERROR: wxglade.py not found!"
   exit 1
 fi
 
 # exec wxGlade
-exec ${PYTHON_BIN} "${WXG_PATH}" "$@"
+exec "${PYTHON_BIN}" "${WXG_BINARY}" "$@"
